"""Constants for Ariston component."""

VERSION = "1.3.6"

# sensor names and values
SENSOR_ACCOUNT_CH_GAS = "Account CH Gas Use"
SENSOR_ACCOUNT_CH_ELECTRICITY = "Account CH Electricity Use"
SENSOR_ACCOUNT_DHW_GAS = "Account DHW Gas Use"
SENSOR_ACCOUNT_DHW_ELECTRICITY = "Account DHW Electricity Use"
SENSOR_CH_ANTIFREEZE_TEMPERATURE = "CH Antifreeze Temperature"
SENSOR_CH_DETECTED_TEMPERATURE = "CH Detected Temperature"
SENSOR_CH_MODE = "CH Mode"
SENSOR_CH_SET_TEMPERATURE = "CH Set Temperature"
SENSOR_CH_PROGRAM = "CH Time Program"
SENSOR_CH_COMFORT_TEMPERATURE = "CH Comfort Temperature"
SENSOR_CH_ECONOMY_TEMPERATURE = "CH Economy Temperature"
SENSOR_DHW_COMFORT_FUNCTION = "DHW Comfort Function"
SENSOR_DHW_PROGRAM = "DHW Time Program"
SENSOR_DHW_SET_TEMPERATURE = "DHW Set Temperature"
SENSOR_DHW_STORAGE_TEMPERATURE = "DHW Storage Temperature"
SENSOR_DHW_COMFORT_TEMPERATURE = "DHW Comfort Temperature"
SENSOR_DHW_ECONOMY_TEMPERATURE = "DHW Economy Temperature"
SENSOR_DHW_MODE = "DHW Mode"
SENSOR_ERRORS = "Active Errors"
SENSOR_HEATING_LAST_24H = "Energy use for Heating in last 24 hours"
SENSOR_HEATING_LAST_7d = "Energy use for Heating in last 7 days"
SENSOR_HEATING_LAST_30d = "Energy use for Heating in last 30 days"
SENSOR_HEATING_LAST_365d = "Energy use for Heating in last 365 days"
SENSOR_MODE = "Mode"
SENSOR_OUTSIDE_TEMPERATURE = "Outside Temperature"
SENSOR_SIGNAL_STRENGTH = "Signal Strength"
SENSOR_WATER_LAST_24H = "Energy use for Water in last 24 hours"
SENSOR_WATER_LAST_7D = "Energy use for Water in last 7 days"
SENSOR_WATER_LAST_30D = "Energy use for Water in last 30 days"
SENSOR_WATER_LAST_365D = "Energy use for Water in last 365 days"
SENSOR_UNITS = "Units of Measurement"
SENSOR_THERMAL_CLEANSE_CYCLE = "Thermal Cleanse Cycle"
SENSOR_GAS_TYPE = "Gas Type"
SENSOR_GAS_COST = "Gas Cost"
SENSOR_ELECTRICITY_COST = "Electricity Cost"

BINARY_SENSOR_CH_FLAME = "CH Flame"
BINARY_SENSOR_DHW_FLAME = "DHW Flame"
BINARY_SENSOR_CH_AUTO_FUNCTION = "CH Auto Function"
BINARY_SENSOR_HOLIDAY_MODE = "Holiday Mode"
BINARY_SENSOR_ONLINE = "Online"
BINARY_SENSOR_FLAME = "Flame"
BINARY_SENSOR_HEAT_PUMP = "Heat Pump"
BINARY_SENSOR_CHANGING_DATA = "Changing Data"
BINARY_SENSOR_INTERNET_TIME = "Internet Time"
BINARY_SENSOR_INTERNET_WEATHER = "Internet Weather"
BINARY_SENSOR_THERMAL_CLEANSE_FUNCTION = "Thermal Cleanse Function"
BINARY_SENSOR_CH_PILOT = "CH Pilot"
BINARY_SENSOR_UPDATE = "Update Available"

SWITCH_POWER = "Power"

VAL_HOLIDAY = "holiday"
VAL_WINTER = "winter"
VAL_SUMMER = "summer"
VAL_OFF = "off"
VAL_HEATING_ONLY = "heating_only"
VAL_SUMMER_MANUAL = "summer_manual"
VAL_SUMMER_PROGRAM = "summer_program"
VAL_WINTER_MANUAL = "winter_manual"
VAL_WINTER_PROGRAM = "winter_program"
VAL_MANUAL = "manual"
VAL_PROGRAM = "program"
VAL_LEARNING = "pilot"
VAL_UNKNOWN = "unknown"
VAL_OFFLINE = "offline"
VAL_NOT_READY = "initiating"
VAL_UNSUPPORTED = "unsupported"
VAL_AVAILABLE = "available"
VAL_DISABLED = "disabled"
VAL_TIME_BASED = "time_based"
VAL_ALWAYS_ACTIVE = "always_active"
VAL_METRIC = "metric"
VAL_IMPERIAL = "imperial"
VAL_AUTO = "auto"
VAL_NORMAL = "normal"
VAL_LONG = "long"

LANG_UK = "uk"
LANG_EN = "en"
LANG_PL = "pl"
LANG_LIST = [LANG_UK, LANG_EN, LANG_PL]
LANG_LOCATION = "/config/custom_components/ariston/.translations/"

DOMAIN = "ariston"
DATA_ARISTON = DOMAIN
DEVICES = "devices"
SERVICE_SET_DATA = "set_data"
SERVICE_UPDATE = "update"
CLIMATES = "climates"
WATER_HEATERS = "water_heaters"

# sensors
PARAM_ACCOUNT_CH_GAS = "account_ch_gas"
PARAM_ACCOUNT_CH_ELECTRICITY = "account_ch_electricity"
PARAM_ACCOUNT_DHW_GAS = "account_dhw_gas"
PARAM_ACCOUNT_DHW_ELECTRICITY = "account_dhw_electricity"
PARAM_CH_ANTIFREEZE_TEMPERATURE = "ch_antifreeze_temperature"
PARAM_CH_MODE = "ch_mode"
PARAM_CH_SET_TEMPERATURE = "ch_set_temperature"
PARAM_CH_COMFORT_TEMPERATURE = "ch_comfort_temperature"
PARAM_CH_ECONOMY_TEMPERATURE = "ch_economy_temperature"
PARAM_CH_DETECTED_TEMPERATURE = "ch_detected_temperature"
PARAM_CH_PROGRAM = "ch_program"
PARAM_ERRORS = "errors"
PARAM_DHW_COMFORT_FUNCTION = "dhw_comfort_function"
PARAM_DHW_MODE = "dhw_mode"
PARAM_DHW_PROGRAM = "dhw_program"
PARAM_DHW_SET_TEMPERATURE = "dhw_set_temperature"
PARAM_DHW_STORAGE_TEMPERATURE = "dhw_storage_temperature"
PARAM_DHW_COMFORT_TEMPERATURE = "dhw_comfort_temperature"
PARAM_DHW_ECONOMY_TEMPERATURE = "dhw_economy_temperature"
PARAM_HEATING_LAST_24H = "heating_last_24h"
PARAM_HEATING_LAST_7d = "heating_last_7d"
PARAM_HEATING_LAST_30d = "heating_last_30d"
PARAM_HEATING_LAST_365d = "heating_last_365d"
PARAM_MODE = "mode"
PARAM_OUTSIDE_TEMPERATURE = "outside_temperature"
PARAM_SIGNAL_STRENGTH = "signal_strength"
PARAM_WATER_LAST_24H = "water_last_24h"
PARAM_WATER_LAST_7D = "water_last_7d"
PARAM_WATER_LAST_30D = "water_last_30d"
PARAM_WATER_LAST_365D = "water_last_365d"
PARAM_UNITS = "units"
PARAM_THERMAL_CLEANSE_CYCLE = "dhw_thermal_cleanse_cycle"
PARAM_GAS_TYPE = "gas_type"
PARAM_GAS_COST = "gas_cost"
PARAM_ELECTRICITY_COST = "electricity_cost"

# binary sensors
PARAM_CH_AUTO_FUNCTION = "ch_auto_function"
PARAM_CH_FLAME = "ch_flame"
PARAM_DHW_FLAME = "dhw_flame"
PARAM_FLAME = "flame"
PARAM_HEAT_PUMP = "heat_pump"
PARAM_HOLIDAY_MODE = "holiday_mode"
PARAM_INTERNET_TIME = "internet_time"
PARAM_INTERNET_WEATHER = "internet_weather"
PARAM_ONLINE = "online"
PARAM_CHANGING_DATA = "changing_data"
PARAM_THERMAL_CLEANSE_FUNCTION = "dhw_thermal_cleanse_function"
PARAM_CH_PILOT = "ch_pilot"
PARAM_UPDATE = "update"

# switches
PARAM_POWER = "power"

# grouping of parameters per request
GET_REQUEST_CH_PROGRAM = [
    PARAM_CH_PROGRAM
]
GET_REQUEST_CURRENCY = [
    PARAM_GAS_TYPE,
    PARAM_GAS_COST,
    PARAM_ELECTRICITY_COST
]
GET_REQUEST_DHW_PROGRAM = [
    PARAM_DHW_PROGRAM
]
GET_REQUEST_ERRORS = [
    PARAM_ERRORS
]
GET_REQUEST_GAS = [
    PARAM_ACCOUNT_CH_GAS,
    PARAM_ACCOUNT_CH_ELECTRICITY,
    PARAM_ACCOUNT_DHW_GAS,
    PARAM_ACCOUNT_DHW_ELECTRICITY,
    PARAM_HEATING_LAST_24H,
    PARAM_HEATING_LAST_7d,
    PARAM_HEATING_LAST_30d,
    PARAM_HEATING_LAST_365d,
    PARAM_WATER_LAST_24H,
    PARAM_WATER_LAST_7D,
    PARAM_WATER_LAST_30D,
    PARAM_WATER_LAST_365D
]
GET_REQUEST_MAIN = [
    PARAM_POWER,
    PARAM_CH_DETECTED_TEMPERATURE,
    PARAM_CH_ANTIFREEZE_TEMPERATURE,
    PARAM_CH_MODE,
    PARAM_CH_SET_TEMPERATURE,
    PARAM_DHW_SET_TEMPERATURE,
    PARAM_MODE,
    PARAM_DHW_COMFORT_TEMPERATURE,
    PARAM_DHW_ECONOMY_TEMPERATURE,
    PARAM_DHW_STORAGE_TEMPERATURE,
    PARAM_OUTSIDE_TEMPERATURE,
    PARAM_DHW_MODE,
    PARAM_HOLIDAY_MODE,
    PARAM_ONLINE,
    PARAM_HEAT_PUMP,
    PARAM_CH_PILOT,
    PARAM_CH_FLAME,
    PARAM_DHW_FLAME,
    PARAM_FLAME
]
GET_REQUEST_PARAM = [
    PARAM_INTERNET_TIME,
    PARAM_INTERNET_WEATHER,
    PARAM_THERMAL_CLEANSE_FUNCTION,
    PARAM_CH_AUTO_FUNCTION,
    PARAM_DHW_COMFORT_FUNCTION,
    PARAM_CH_COMFORT_TEMPERATURE,
    PARAM_CH_ECONOMY_TEMPERATURE,
    PARAM_SIGNAL_STRENGTH,
    PARAM_THERMAL_CLEANSE_CYCLE
]
GET_REQUEST_UNITS = [
    PARAM_UNITS
]
GET_REQUEST_VERSION = [
    PARAM_UPDATE
]

SET_REQUEST_MAIN = [
    PARAM_POWER,
    PARAM_CH_DETECTED_TEMPERATURE,
    PARAM_CH_ANTIFREEZE_TEMPERATURE,
    PARAM_CH_MODE,
    PARAM_CH_SET_TEMPERATURE,
    PARAM_DHW_SET_TEMPERATURE,
    PARAM_MODE,
    PARAM_DHW_STORAGE_TEMPERATURE,
    PARAM_OUTSIDE_TEMPERATURE,
    PARAM_DHW_MODE,
    PARAM_HOLIDAY_MODE,
    PARAM_ONLINE,
    PARAM_HEAT_PUMP,
    PARAM_CH_PILOT,
    PARAM_CH_FLAME,
    PARAM_FLAME
]
SET_REQUEST_PARAM = [
    PARAM_INTERNET_TIME,
    PARAM_INTERNET_WEATHER,
    PARAM_THERMAL_CLEANSE_FUNCTION,
    PARAM_CH_AUTO_FUNCTION,
    PARAM_DHW_COMFORT_FUNCTION,
    PARAM_DHW_COMFORT_TEMPERATURE,
    PARAM_DHW_ECONOMY_TEMPERATURE,
    PARAM_CH_COMFORT_TEMPERATURE,
    PARAM_CH_ECONOMY_TEMPERATURE,
    PARAM_SIGNAL_STRENGTH,
    PARAM_THERMAL_CLEANSE_CYCLE
]
SET_REQUEST_UNITS = [
    PARAM_UNITS
]


ARISTON_DHW_COMFORT_TEMP = "U6_9_0"
ARISTON_DHW_COMFORT_FUNCTION = "U6_9_2"
ARISTON_DHW_TIME_PROG_COMFORT = "U6_9_1_0_0"
ARISTON_DHW_TIME_PROG_ECONOMY = "U6_9_1_0_1"
ARISTON_SIGNAL_STRENGHT = "U6_16_5"
ARISTON_INTERNET_TIME = "U6_16_6"
ARISTON_INTERNET_WEATHER = "U6_16_7"
ARISTON_CH_COMFORT_TEMP = "U6_3_1_0_0"
ARISTON_CH_ECONOMY_TEMP = "U6_3_1_0_1"
ARISTON_CH_AUTO_FUNCTION = "U6_3_3"
ARISTON_THERMAL_CLEANSE_FUNCTION = "U6_9_5_0"
ARISTON_THERMAL_CLEANSE_CYCLE = "U6_9_5_1"
ARISTON_S_W_FUNCTION_ACTIVATION = "U6_3_5_0_0"
ARISTON_S_W_TEMPERATURE_THRESHOLD = "U6_3_5_0_1"
ARISTON_S_W_DELAY_TIME = "U6_3_5_0_2"

ARISTON_CH_COMFORT_TEMP_ZONE_2 = "U6_3_1_1_0"
ARISTON_CH_ECONOMY_TEMP_ZONE_2 = "U6_3_1_1_1"
ARISTON_CH_COMFORT_TEMP_ZONE_3 = "U6_3_1_2_0"
ARISTON_CH_ECONOMY_TEMP_ZONE_3 = "U6_3_1_2_1"
ARISTON_S_W_FUNCTION_ACTIVATION_ZONE_2 = "U6_3_5_1_0"
ARISTON_S_W_TEMPERATURE_THRESHOLD_ZONE_2 = "U6_3_5_1_1"
ARISTON_S_W_DELAY_TIME_ZONE_2 = "U6_3_5_1_2"
ARISTON_S_W_FUNCTION_ACTIVATION_ZONE_3 = "U6_3_5_2_0"
ARISTON_S_W_TEMPERATURE_THRESHOLD_ZONE_3 = "U6_3_5_2_1"
ARISTON_S_W_DELAY_TIME_ZONE_3 = "U6_3_5_2_2"

ARISTON_PARAM_LIST = [
    ARISTON_DHW_COMFORT_TEMP,
    ARISTON_DHW_COMFORT_FUNCTION,
    ARISTON_DHW_TIME_PROG_COMFORT,
    ARISTON_DHW_TIME_PROG_ECONOMY,
    ARISTON_SIGNAL_STRENGHT,
    ARISTON_INTERNET_TIME,
    ARISTON_INTERNET_WEATHER,
    ARISTON_CH_COMFORT_TEMP,
    ARISTON_CH_ECONOMY_TEMP,
    ARISTON_CH_AUTO_FUNCTION
]

UNKNOWN_TEMP = [0, 3276]
DAYS_OF_WEEK = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]

CONF_HVAC_OFF = "hvac_off"
CONF_POWER_ON = "power_on"
CONF_MAX_RETRIES = "max_retries"
CONF_STORE_CONFIG_FILES = "store_config_files"
CONF_CONTROL_FROM_WATER_HEATER = "control_from_water_heater"
CONF_HVAC_OFF_PRESENT = "hvac_off_present"
CONF_LOCALIZATION = "localization"
CONF_UNITS = "units"
CONF_POLLING_RATE = "polling_rate"
CONF_INIT_AT_START = "init_during_start"
CONF_DHW_FLAME_UNKNOWN_ON = "dhw_flame_unknown_as_on"

MODE_TO_VALUE = {VAL_WINTER: 1, VAL_SUMMER: 0, VAL_OFF: 5, VAL_HEATING_ONLY: 2}
VALUE_TO_MODE = {1: VAL_WINTER, 0: VAL_SUMMER, 5: VAL_OFF, 2: VAL_HEATING_ONLY}
CH_MODE_TO_VALUE = {VAL_MANUAL: 2, VAL_PROGRAM: 3, VAL_UNKNOWN: 0}
VALUE_TO_CH_MODE = {2: VAL_MANUAL, 3: VAL_PROGRAM, 0: VAL_UNKNOWN}
DHW_MODE_TO_VALUE = {VAL_MANUAL: 2, VAL_PROGRAM: 1}
VALUE_TO_DHW_MODE = {2: VAL_MANUAL, 1: VAL_PROGRAM, 0: VAL_UNSUPPORTED}
DHW_COMFORT_FUNCT_TO_VALUE = {VAL_DISABLED: 0, VAL_TIME_BASED: 1, VAL_ALWAYS_ACTIVE: 2}
DHW_COMFORT_VALUE_TO_FUNCT = {0: VAL_DISABLED, 1: VAL_TIME_BASED, 2: VAL_ALWAYS_ACTIVE}
UNIT_TO_VALUE = {VAL_METRIC: 0, VAL_IMPERIAL: 1}
VALUE_TO_UNIT = {0: VAL_METRIC, 1: VAL_IMPERIAL}
PARAM_STRING_TO_VALUE = {"true": 1, "false": 0}