set_data:
  description: Set Ariston Data via HTTP
  fields:
    entity_id:
      description: "(Mandatory) Climate 'enity_id' for Ariston heater"
      example: climate.ariston
    mode:
      description: "(Optional) General mode: 'winter' or 'summer' or 'off' or 'heating only'. Values depend on model."
      example: winter
    ch_mode:
      description: "(Optional) CH mode: 'manual' or 'scheduled' or 'intelligent'. Values depend on model."
      example: manual
    dhw_mode:
      description: "(Optional) DHW mode: 'manual' or 'scheduled'. Values depend on model."
      example: manual
    ch_set_temperature:
      description: "(Optional) Set CH temperature in C in steps of '0.5'. Value range depends on model."
      example: 21.5
    ch_scheduled_comfort_temperature:
      description: "(Optional) Set CH Scheduled Comfort temperature in C in steps of '0.5'. Value range depends on model."
      example: 23
    ch_scheduled_economy_temperature:
      description: "(Optional) Set CH Scheduled Economy temperature in C in steps of '0.5'. Value range depends on model."
      example: 23.5
    dhw_comfort_function:
      description: "(Optional) DHW Comfort Function: 'disabled' or 'time based' or 'always active'"
      example: 'disabled'
    dhw_set_temperature:
      description: "(Optional) Set DHW temperature in C in steps of '1.0'. Value range depends on model."
      example: 46
    dhw_scheduled_comfort_temperature:
      description: "(Optional) Set DHW Scheduled Comfort temperature in C in steps of '1.0'. Value range depends on model."
      example: 46
    dhw_scheduled_economy_temperature:
      description: "(Optional) Set DHW Scheduled Economy temperature in C in steps of '1.0'. Value range depends on model."
      example: 46
    internet_time:
      description: "(Optional) enable or disable time from internet"
      example: true
    internet_weather:
      description: "(Optional) enable or disable weather from internet"
      example: true